### PR TITLE
Cache bundler

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by tfausak** [comment]
:+1: This makes things twice as fast. Thanks!

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am interested in understanding why caching hasn't been enabled before this pull request (i.e., since [December 17, 2014, when it became available to open source projects](https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure)).

Thank you.

**Comment by tfausak** [comment]
You're asking, more than five years later, why it took us a little more than a year to enable caching on CI? In a word: inertia. Caching wasn't available, so we set it up without caching. It worked, so we didn't touch it. Someone noticed that it could use the new caching feature, so we updated it.

**Comment by Taher-Ghaleb** [comment]
I got your point. Thank you so much, @tfausak, for your gentle responsiveness.

**Pull request merged**
