### PR TITLE
Replace white/blacklists with error hanlder and never re-raise errors

### PR DESCRIPTION
**Pull request by zeisler**
@tfausak Checkout this PR when you have a chance. Thanks!

### CODE REVIEW

**Comment by zeisler** [comment]
Github is not showing the most up to date version of my branch.

**Comment by zeisler** [comment]
It seem to be up-to-date now.

**Comment by zeisler** [comment]
Do you have any feedback on this? @tfausak

**Comment by tfausak** [comment]
I'm sorry it took me so long to look at this. I like some of what you've done here. In particular I think sending the error to a method in Stoplight (via `handler.handle` right now) is a good way to keep the sane default behavior around. I don't like creating all these modules and instances just to check a value against a function. 

This feels like a good improvement on my work in #97. I want to think a little more about how to handle the fallback case without so much `.new`.

**Comment by tfausak** [comment]
I am going with #97 instead of this or #99. Thanks again for your help!

**Pull request closed without merging**
